config/routes.rb
SampleApp::Application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'
  resources :search, only: [:search_params, :searching]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update] 
  resources :microposts, only: [:create, :destroy]
  resources :fotitos, only: [:create,:destroy]
  

  resources :messages
  

  resources :teachers

  resources :subjects

  
  
  
  root 'users#all_projects'
  get 'logout' => 'sessions#destroy'
  get 'AllProjects' => "users#all_projects" 
  get 'NewProject' => 'users#create_project', :as => "create_project"
  get 'index' => 'users#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'users/:id/details', to: 'users#details', :as => 'details'
  get 'microposts/:id', to: 'microposts#show', :as => "project"
  get 'users/:id/profile', to: 'users#profile', :as => 'profile'
  get 'new_project' => 'users#new_project'
  post 'AddTeam' => 'microposts#TeamUpdate'
  post 'NewNote' => 'microposts#NewNote'
  post 'upload' => 'microposts#NewFile'
  get 'search/index' => 'search#search'
  get 'project/delete' => 'microposts#destroy', :as => 'project_destroy'
  get 'note/delete' => 'microposts#DestroyNote', :as => 'note_destroy'
  get 'project/join' => 'microposts#join', :as => 'join'
  post 'TeacherNote' => 'teachers#NewNote'
  post 'AddClass' => 'teachers#AddClass'
  post 'ClassNote' => 'subjects#NewNote'
  post 'ClassFile' => 'subjects#NewFile'
  post 'JoinClass' => 'users#JoinClass', :as => 'JoinClass'
  get 'DeleteFile' => 'subjects#DestroyFile', :as => 'killfile'
  post 'NewLike' => 'teachers#NoteLike'
  post 'SubjectLike' => 'subjects#NoteLike'
  post 'KillLike' => 'teachers#UnLike'
  post 'SubKillLike' => 'subjects#UnLike'
  get 'profile_picture' => 'pictures#profile_picture'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount ActionCable.server, at: '/cable'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @user = User.find(current_user.id)
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
    if logged_in?
      @user = User.find(current_user.id)
      @microposts = Micropost.all.paginate(page: params[:page])
    end
  end

  def about
    if logged_in?
      @user = User.find(current_user.id)
    else
      redirect_to '/login'
    end
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<div class="container">
    <div class= "row justify-content-center">
        <div class = "col-lg-11 col-xl-9">
            <section class="py-4 py-lg-5">
            <div class="mb-3 d-flex">
                <img alt="Pipeline" src="/pages/assets/img/logo-color.svg" class="avatar avatar-lg mr-1">
            </div>
                <h1 class="display-4 mb-3">Welcome to Connect4G</h1>
                <%# <div class= "mb-3 d-flex"> %>
                <div class="carousel-inner overflow-visible">
                    <div class = "shadow-lg">
                        <img alt="Image" src= "/founder.jpeg", class = "img-fluid rounded border">
                    </div>
                </div>
                <div class= "align-items-center mb-3">
                    <p class= "lead">
                    </p>
                    <p class="lead">
        

                        Connect4G compiles everyone's information in order to connect motivated individuals. If you want to build a team of people who understand
                        finance, are capable of analyzing data, and speak Spanish, then going to Connect4G is the best way to find them.
                        After confirming your email, you will get complete access to our database. You will then have the ability to connect
                        with every individual in the network. Hopefully, you will connect for good.
                    </p>
                    <p class="lead">
                    I also wish that you have as much fun building things with each other as I did building this.
                    </p>
                    <p class="lead">
                    Kenton Blacutt
                    </p>
                </div>
            </section>
        </div>
    </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  If you are interested in Connect4G send an email to <%=mail_to "connect4g@connect4g.com" %>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Projects")%>
<h1 id = 'projects'>Projects</h1>
<%if logged_in?%>
    <div>

    <h3><%= link_to 'Link to Add Your Own Project', new_project_url%> </h3>
    </div>
    <% if @microposts.any? %>
      <h3> Open Projects</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  <%else%>
  <p id= "blurb">
    One day this page will be filled with tales of successful projects that revolutionized the world. Yet until that day, we're left with this.
  </p>
<%end%>

app/views/static_pages/home.html.erb
<% if logged_in?%>
<% else %>
  <div class="center jumbotron"s>
    <h1>Welcome to Connect4G</h1>
    <h1></h1>

    <%= link_to "Get started now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<%end%>