config/routes.rb
SampleApp::Application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'
  resources :search, only: [:search_params, :searching]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update] 
  resources :microposts, only: [:create, :destroy]
  resources :fotitos, only: [:create,:destroy]
  

  resources :messages
  

  resources :teachers

  resources :subjects

  
  
  
  root 'users#all_projects'
  get 'logout' => 'sessions#destroy'
  get 'AllProjects' => "users#all_projects" 
  get 'NewProject' => 'users#create_project', :as => "create_project"
  get 'index' => 'users#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'users/:id/details', to: 'users#details', :as => 'details'
  get 'microposts/:id', to: 'microposts#show', :as => "project"
  get 'users/:id/profile', to: 'users#profile', :as => 'profile'
  get 'new_project' => 'users#new_project'
  post 'AddTeam' => 'microposts#TeamUpdate'
  post 'NewNote' => 'microposts#NewNote'
  post 'upload' => 'microposts#NewFile'
  get 'search/index' => 'search#search'
  get 'project/delete' => 'microposts#destroy', :as => 'project_destroy'
  get 'note/delete' => 'microposts#DestroyNote', :as => 'note_destroy'
  get 'project/join' => 'microposts#join', :as => 'join'
  post 'TeacherNote' => 'teachers#NewNote'
  post 'AddClass' => 'teachers#AddClass'
  post 'ClassNote' => 'subjects#NewNote'
  post 'ClassFile' => 'subjects#NewFile'
  post 'JoinClass' => 'users#JoinClass', :as => 'JoinClass'
  get 'DeleteFile' => 'subjects#DestroyFile', :as => 'killfile'
  post 'NewLike' => 'teachers#NoteLike'
  post 'SubjectLike' => 'subjects#NoteLike'
  post 'KillLike' => 'teachers#UnLike'
  post 'SubKillLike' => 'subjects#UnLike'
  get 'profile_picture' => 'pictures#profile_picture'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount ActionCable.server, at: '/cable'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  before_action :logged_in_user

  def search
    @user = User.find(current_user.id)
    @users = User.all
    @criteria = params[:search].split
    for term in @criteria do
      if params[:search]
        @users = @users.search(term).order("created_at DESC")
      else
        @users = @users.all.order("created_at DESC")
      end
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_index.html.erb
<div class="input-group input-group-dark input-group-round">
    <div class="input-group-prepend">
        <%# <span class="input-group-text">
            <i class="material-icons">search</i>
        </span> %>
    </div>
    <%= form_tag(search_index_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search the database", class: "form-control fontrol-dark" %>
    <% end %>
    <%# input type="search" class="form-control form-control-dark" placeholder="Search" aria-label="Search app" aria-describedby="search-app"> %>
</div>

app/views/search/search.html.erb
<div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-11 col-xl-9">
                            <section class="py-4 py-lg-5">
                        
                                <h1 class="display-4 mb-3">Search Results</h1>
                                <p class="lead">
                                    Anyone familiar with your search criteria will be listed below
                                </p>
                            </section>
                            <section>
                              
                              <%@users.each do |u|%>
                              
                                <div class="row">
                                  <%@name = u.first_name + ' ' + u.last_name%>
                                  <%=link_to u, data_toggle: "tooltip", title: @name do%>
                                    
                                    <%if u.picture%>
                                      <%unless u.picture.url.nil?%>
                                        <%= image_tag u.picture.url, class: "avatar avatar-lg", data_title: @name, data_toggle: "tooltip", alt:"image"%>
                                    <%# <img alt="Image" src="/avatar" class="avatar avatar-lg" data-title="Peggy Brown" data-toggle="tooltip" /> %>
                                        <%else%>
                                      <%= image_tag "/avatar.png", class: "avatar avatar-lg", data_title: @name, data_toggle: "tooltip", alt:"image"%>
                                    <%end%>
                                    <%else%>
                                      <%= image_tag "/avatar.png", class: "avatar avatar-lg", data_title: @name, data_toggle: "tooltip", alt:"image"%>
                                    <%end%>
                                  <%end%>  
                                </div>
                              <%end%>  
                            </section>
                        </div>
                    </div>
                </div>

                                

app/views/search/search_copy.html.erb
<h3>Search Results</h3>
<ul class="users">
    <%= render @users %>
</ul>
<% if @users.blank? %>
  <h4>No results were found for <%= params[:search] %>.</h4>
<% end %>