config/routes.rb
SampleApp::Application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'
  resources :search, only: [:search_params, :searching]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update] 
  resources :microposts, only: [:create, :destroy]
  resources :fotitos, only: [:create,:destroy]
  

  resources :messages
  

  resources :teachers

  resources :subjects

  
  
  
  root 'users#all_projects'
  get 'logout' => 'sessions#destroy'
  get 'AllProjects' => "users#all_projects" 
  get 'NewProject' => 'users#create_project', :as => "create_project"
  get 'index' => 'users#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'users/:id/details', to: 'users#details', :as => 'details'
  get 'microposts/:id', to: 'microposts#show', :as => "project"
  get 'users/:id/profile', to: 'users#profile', :as => 'profile'
  get 'new_project' => 'users#new_project'
  post 'AddTeam' => 'microposts#TeamUpdate'
  post 'NewNote' => 'microposts#NewNote'
  post 'upload' => 'microposts#NewFile'
  get 'search/index' => 'search#search'
  get 'project/delete' => 'microposts#destroy', :as => 'project_destroy'
  get 'note/delete' => 'microposts#DestroyNote', :as => 'note_destroy'
  get 'project/join' => 'microposts#join', :as => 'join'
  post 'TeacherNote' => 'teachers#NewNote'
  post 'AddClass' => 'teachers#AddClass'
  post 'ClassNote' => 'subjects#NewNote'
  post 'ClassFile' => 'subjects#NewFile'
  post 'JoinClass' => 'users#JoinClass', :as => 'JoinClass'
  get 'DeleteFile' => 'subjects#DestroyFile', :as => 'killfile'
  post 'NewLike' => 'teachers#NoteLike'
  post 'SubjectLike' => 'subjects#NoteLike'
  post 'KillLike' => 'teachers#UnLike'
  post 'SubKillLike' => 'subjects#UnLike'
  get 'profile_picture' => 'pictures#profile_picture'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount ActionCable.server, at: '/cable'

end

app/models/user.rb
class User < ApplicationRecord
    has_many :fotitos, dependent: :destroy
    has_and_belongs_to_many :subjects
    has_and_belongs_to_many :microposts, dependent: :destroy
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    before_save { self.email = email.downcase }
    validates :first_name,  presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    attr_accessor :validation_code, :flash_notice
    validate :nyu_edu
    mount_uploader :picture, PictureUploader
    has_many :likes
    has_many :liked_notes, through: :likes, source: :note

    class << self
    # Returns the hash digest of the given string.
        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                            BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
        end

        def new_token
            SecureRandom.urlsafe_base64
        end
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

  # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

      # Activates an account.
    def activate
        update_attribute(:activated,    true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    def feed
      Micropost.where("user_id = ?", id)
    end

    def self.search(search)
        User.where("first_name LIKE ? OR last_name LIKE ? OR technical LIKE ? OR spoken_languages LIKE ? OR other LIKE ? or connections LIKE ? or internships LIKE ? or campus LIKE ? or major LIKE ? or experience LIKE ? or interests LIKE ? or minor LIKE ? or position LIKE ?","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%","%#{search}%","%#{search}%","%#{search}%") 
    end

    # Makes sure it's an NYU Email

    def nyu_edu
      @domain = self.email.split('@')[1]
      errors.add(:base, 'For now we only support New York University') unless @domain == 'nyu.edu'
    end

    #Push Notifications

    def push_notification
        UserMailer.new_message(self).deliver_now
    end

    private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :details]
  before_action :admin_user, only: :destroy

  def index
    if logged_in?
      # byebug
      @subjects = Subject.all
      @users = User.order(:name).paginate(page: params[:page])
      @user = User.find(current_user.id)
      @project = current_user.microposts.build(micropost_params)
      if @project.save
        @user.microposts << @project
        flash[:success] = "Project created succesfully!"
        redirect_to current_user
      else
        render 'index'
      end
    else
      redirect_to login_url
    end
  end


  def all_projects
    if logged_in?
      @user = User.find(current_user.id)
      @projects = Micropost.all
    else
      redirect_to login_url
    end
  end



  def create_project
    @users = User.order(:name).paginate(page: params[:page])
    @user = User.find(current_user.id)
    @project = current_user.microposts.build(micropost_params)
    if logged_in?
      @users = User.order(:name).paginate(page: params[:page])
      @user = User.find(current_user.id)
      @project = current_user.microposts.build(micropost_params)
      
      if @project.save
        @user.microposts << @project
        
        # @project.users << @user.microposts
        # @project.users.each do |s|
          
          # @project << s
          # s << @project

        # end
        flash[:success] = "Project created succesfully!"
        render 'index'
      else
        render 'microposts#create_project'
      end
    else
      redirect_to login_url
    end
  end
  
  def show
    @user = User.find(params[:id])
    @projects = @user.microposts
  end

  def profile
    @user = User.find(params[:id])
    render 'profile'
  end

  def new
    @user = User.new
  end

  def details
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    # byebug
    if @user.update_attributes(update_params)
      # flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end 
  end

  def search_params
    params.permit(:campus, :major, :experience,
      :year, :interests)
    @search_params = params
  end

  def new_project
    @user = User.find(current_user.id)
    @micropost  = current_user.microposts.build
  end

  def edit
    # include FotitosController
    # byebug
    @user = User.find(params[:id])
    # if @user.update_attributes(user_params)
    #   # flash[:success] = "Profile updated"
    #   redirect_to @user
    # else
    #   render 'edit'
    # end
  end

  def profile_picture
    # @picture = 
  end


  def JoinClass
    @class = Subject.find(params[:subject])
    unless @class.users.include?(current_user)
      current_user.subjects << @class
    end
    redirect_to request.referrer
  end
  private

    # def nyu_edu?
    #   @domain = @user.email.split('@')[1]
    #   if @domain != 'nyu.edu'
    #       return true
    #   # end
    #   else
    #       flash[:danger] = "At the moment we only support members of NYU"
    #       return false
    #   end
    # end

    def fotito_params
      params.require(:fotito).permit(:content, :picture)
    end


    def details_params
      params.require(:id).permit(:interests,:technical,:spoken_languages,:other,:connections)
    end

    def user_params
      params.require(:user).permit(:recommendations,:id,:name,:utf8, :authenticity_token, :commit,:first_name,:last_name, :minor, :position, :technical,:spoken_languages,:other,:connections,:internships, :email, :password, :password_confirmation, :campus, :major, :experience,
                                    :year, :interests, :content, :picture, :micropost)
    end

    def update_params
      # byebug
      params.require(:user).permit(:recommendations,:first_name, :last_name, :email, :campus, :other, :interests, :technical, :connections, :spoken_languages, :position, :major, :minor, :year, :internships)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end

    def micropost_params
      params.require(:micropost).permit(:name,:content,:user_id,:public)
    end

    
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/all_projects.html.erb
<div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-11 col-xl-9">
                            <section class="py-4 py-lg-5">
                                <div class="mb-3 d-flex">
                                    <img alt="Pipeline" src="https://goodlogo.com/images/logos/new_york_university_nyu_logo_3400.gif" class="avatar avatar-lg mr-1">
                                    
                                </div>
                                <h1 class="display-4 mb-3">New York University</h1>
                                <p class="lead">
                                    All the projects open to members of NYU are listed below
                                </p>
                            </section>
                            <section>
                                <div class="row">
                                <%unless @projects.nil?%>
                                                
    
                                                <%@projects.each do |project|%>
                                                <%if project.public%>
                                                <div class="col-lg-6">
                                                    <div class="card card-project">

                                                        <%# <div class="progress">
                                                            <div class="progress-bar bg-danger" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                                                        </div> %>
                                                        
                                                        <div class="card-body">
                                                            <div class="dropdown card-options">
                                                                <button class="btn-options" type="button" id="project-dropdown-button-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                    <i class="material-icons">more_vert</i>
                                                                </button>
                                                                <div class="dropdown-menu dropdown-menu-right">
                                                                <%unless project.users.include?(current_user)%>
                                                                    <%= link_to 'Join', join_url(:id => project.id), class: "dropdown-item"%>
                                                                <%end%>
                                                                <%if project.user_id == current_user.id%>
                                                                        <%= link_to 'Delete', project_destroy_url(:id => project.id), class: "dropdown-item text-danger"%>
                                                                <%end%>
                                                                    <%# <a class="dropdown-item" href="#">Join</a> %>
                                                                    <a class="dropdown-item" href="#">Share</a>
                                                                </div>
                                                            </div>
                                                            <div class="card-title">
                                                                <a href="#">
                                                                
                                                                    <h5 data-filter-by="text"><%= project.name%></h5>
                                                                </a>
                                                            </div>
                                                            <p class="card-text"><%=project.content%></p>
                                                            
                                                            <ul class="avatars">
                                                            <%project.users.each do |u| %>
                                                                <li>
                                                                    <%= link_to u, data_toggle:"tooltip", title: u.first_name do%>
                                                                    <%unless u.picture.nil?%>
                                                                        <%unless u.picture.url.nil?%>
                                                                            <%= image_tag u.picture.url, class: "avatar", alt: u.first_name, data_filter_by: "alt"%>
                                                                        <%else%>
                                                                            <%= image_tag "/avatar.png", class: "avatar", alt: u.first_name, data_filter_by: "alt"%>
                                                                        <%end%>
                                                                    <%else%>
                                                                    <%# <a href="#" data-toggle="tooltip" title="Kenny"> %>
                                                                        <%= image_tag "/avatar.png", class: "avatar", alt:u.first_name, data_filter_by: "alt"%>
                                                                        <%# <img alt="Kenny Tran" class="avatar" src="pages/assets/img/avatar-male-6.jpg" data-filter-by="alt" > %>
                                                                    </a>
                                                                        <%end%>
                                                                    <%end%>
                                                                    
                                                                    <%# <%else%>
                                                                        <%# <%= img "/avatar", class: "avatar", data_filter_by: "alt"%>
                                                                    <%# <%end%>
                                                                </li>

                                                            <%end %>
                                                            </ul>
                                                            
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                                <%end%>
                                            
                                <%end%>
                                <%end%>
                            </section>
                        </div>
                    </div>
                </div>

                                

app/views/users/create_project.html.erb
<%=form_for @project do |f|%>
<%= f.hidden_field :user_id, value: current_user.id%>

<div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">New Project</h5>
            <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
        </div>
        <!--end of modal head-->
        <ul class="nav nav-tabs nav-fill">
            <li class="nav-item">
                <a class="nav-link active" id="project-add-details-tab" data-toggle="tab" href="#project-add-details" role="tab" aria-controls="project-add-details" aria-selected="true">Details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="project-add-members-tab" data-toggle="tab" href="#project-add-members" role="tab" aria-controls="project-add-members" aria-selected="false">Members</a>
            </li>
        </ul>
        <div class="modal-body">
            <div class="tab-content">
                <div class="tab-pane fade show active" id="project-add-details" role="tabpanel" aria-labelledby="project-add-details-tab">
                    <h6>General Details</h6>
                    <div class="form-group row align-items-center">
                        <label class="col-3">Name</label>
                        <%=f.text_field :name, class:"form-control col", placeholder: "Project name"%>
                        <%# <input class="form-control col" type="text" placeholder="Project name" name="project-name" /> %>
                    </div>
                    <div class="form-group row">
                        <%f.label :content, "Description", class: "col-3"%>
                        <label class="col-3">Description</label>
                        <%=f.text_area :content, class:"form-control col", placeholder: "Project description", rows: "3"%>
                        <%# <textarea class="form-control col" rows="3" placeholder="Project description" name="project-description"></textarea> %>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-everyone" name="visibility" class="custom-control-input" checked="">
                                <label class="custom-control-label" for="visibility-everyone">Everyone</label>
                            </div>
                        </div>
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-members" name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility-members">Members</label>
                            </div>
                        </div>
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-me" name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility-me">Just me</label>
                            </div>
                        </div>
                    </div>
                    <%# <hr> %>
                    <%# <h6>Timeline</h6> %>
                    <%# <div class="form-group row align-items-center">
                        <label class="col-3">Start Date</label>
                        <input class="form-control col" type="date" placeholder="Project start" name="project-start" />
                    </div> %>
                    <%# <div class="form-group row align-items-center">
                        <label class="col-3">Due Date</label>
                        <input class="form-control col" type="date" placeholder="Project due" name="project-due" />
                    </div>
                    <div class="alert alert-warning text-small" role="alert">
                        <span>You can change due dates at any time.</span>
                    </div> %>
                    <%# <hr> %>
                    <%# <h6>Visibility</h6> %>
                    <%# <div class="row">
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-everyone" name="visibility" class="custom-control-input" checked>
                                <label class="custom-control-label" for="visibility-everyone">Everyone</label>
                            </div>
                        </div>
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-members" name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility-members">Members</label>
                            </div>
                        </div>
                        <div class="col">
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility-me" name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility-me">Just me</label>
                            </div>
                        </div>
                    </div> %>
                </div>
                <div class="tab-pane fade" id="project-add-members" role="tabpanel" aria-labelledby="project-add-members-tab">
                    <div class="users-manage" data-filter-list="form-group-users">
                        <div class="mb-3">
                            <ul class="avatars text-center">
                                <%@project.users.each do |u|%>

                                <li>
                                    <%if u.picture.url%>
                                    <%= image_tag u.picture.url, alt: u.first_name, class: "avatar", data_toogle: "tooltips", data_title: u.first_name%>
                                    <%else%>
                                        <img alt="Image" src="/avatar.png" class="avatar" />
                                    <%end%>
                                    <%# <img alt="Claire Connors" src="pages/assets/img/avatar-female-1.jpg" class="avatar" data-toggle="tooltip" data-title="Claire Connors" /> %>
                                </li>
                                <%end%>
                                

                            </ul>
                        </div>
                        <div class="input-group input-group-round">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="material-icons">filter_list</i>
                                </span>
                            </div>
                            <input type="search" class="form-control filter-list-input" placeholder="Filter members" aria-label="Filter Members" aria-describedby="filter-members">
                        </div>
                        <div class="form-group-users">
                            <%@project.users.each do |u|%>
                            <div class="custom-control custom-checkbox">
                                
                                <input type="checkbox" class="custom-control-input" id="project-user-1" checked>
                                <label class="custom-control-label" for="project-user-1">
                                    <div class="d-flex align-items-center">
                                        <%unless u.picture.nil?%>
                                            <%= image_tag u.picture.url, alt: u.first_name, class: "avatar mr-2"%>
                                        
                                        <%else%>
                                            <img alt="Image" src="/avatar.png" class="avatar" />
                                        <%end%>
                                        <%# <img alt="Claire Connors" src="pages/assets/img/avatar-female-1.jpg" class="avatar mr-2" /> %>
                                        <span class="h6 mb-0" data-filter-by="text"><%= u.first_name%> <%=u.last_name%></span>
                                    </div>
                                </label>
                            </div>
                            <%end%>
                            
                            <%@all = User.all%>
                            <%@all.each do |e|%>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="project-user-12">
                                <label class="custom-control-label" for="project-user-12">
                                    <div class="d-flex align-items-center">
                                        <%unless e.picture.nil?%>
                                            <%= image_tag e.picture.url, alt: e.first_name, class: "avatar mr-2"%>
                                        
                                        <%else%>
                                            <img alt="Image" src="/avatar.png" class="avatar" />
                                        <%end%>
                                        <span class="h6 mb-0" data-filter-by="text"><%=e.first_name%> <%=e.last_name%></span>
                                    </div>
                                </label>
                            </div>
                            <%end%>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end of modal body-->
        <div class="modal-footer">
            <%= f.submit "Create Project", class: "btn btn-primary"%>
            <%# <button role="button" class="btn btn-primary" type="submit"> %>
                <%# Create Project %>
            <%# </button> %>
        </div>
<%end%>
</div>

app/views/users/details.html.erb
<% provide(:title, 'Experience Details') %>
<h1>Experience</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :year, "Graduation Year" %>
      <%= f.text_field :year, placeholder: '2021', class: 'form-control' %>

      <%= f.label :campus%>
      <%= f.select(:campus) do %>
        <% [['Shanghai', 1], ['New York', 2],['Abu Dhabi',3]].each do |c| -%>
            <%= content_tag(:option, c.first, value: c.first) %>
        <% end %>
      <% end %>

      <%= f.label :major%>
      <%= f.text_field :major, placeholder: 'Global China Studies', class: 'form-control' %>

      <%= f.label :interests%>
      <%= f.text_field :interests, placeholder: 'Literature, Films, and Painting', class: 'form-control' %>

      <%= f.label :internships %>
      <%= f.text_field :internships, placeholder: 'Google', class: 'form-control' %>

      <%= f.label :connections %>
      <%= f.text_field :connections, placeholder: 'Argentinian Bankers', class: 'form-control' %>

      <%= f.label :techincal %>
      <%= f.text_field :technical, placeholder: 'Ruby on Rails', class: 'form-control' %>

      <%= f.label :spoken_languages %>
      <%= f.text_field :spoken_languages, placeholder: 'Dutch',  class: 'form-control' %>

      <%= f.label :other %>
      <%= f.text_field :other, placeholder: 'I made a short YouTube video', class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%end%>
    </div>
  </div>

app/views/users/new_copy.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/original_index.html.erb
<% provide(:title, 'Users') %>
<% if @search_params%>
  <%= @users.where(@search_params) %>
<%else%>
  <h1>All Users</h1>
  <div class="fixed-top-left">
    <%= render '/search/index'%>
  </div>

  <ul class="users">
    <% for i in @users %>
      <%if i.activated%>
        <%= render i%>
      <%end%>
    <%end%>
  </ul>

  <%= will_paginate %>
<%end%>

app/views/users/profile_picture.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>